# This file stores configurations for your Shopify app.

scopes = "write_products,write_orders,read_customer_payment_methods,read_own_subscription_contracts,write_own_subscription_contracts,read_customers"
